{% from "kubernetes/map.jinja" import config with context %}

apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gp2
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  {% if config.default_storage_class_zones is defined and config.default_storage_class_zones|length() > 0 %}
  zones: {{ config.default_storage_class_zones }}
  {% endif %}
