{% set version = "v1.6.0" %}
{% set ips = salt['mine.get']('kubernetes:master', 'network.internal_ip', 'pillar').values() -%}
kubernetes:
  version: {{ version }}
  hyperkube_image: gcr.io/google_containers/hyperkube
  flannel_image: "quay.io/coreos/flannel"
  {% if grains['oscodename'] in [ 'vivid', 'wily', 'jessie', 'xenial', 'yakkety' ] %}
  is_systemd: True
  systemd_system_path: /lib/systemd/system
  {% elif grains['os_family'] == 'RedHat' %}
  is_systemd: True
  systemd_system_path: /usr/lib/systemd/system
  {% else %}
  is_systemd: False
  {% endif %}
  admission_control: "NamespaceLifecycle,NamespaceExists,ServiceAccount,LimitRanger,ResourceQuota,SecurityContextDeny"
  kube_user: "system:anonymous"
  network_provider: "kubenet"
  allow_privileged: true
  log_level: "--v=2"
  kube_docker_registry: "gcr.io/google_containers"
  apiserver_docker_tag: {{ version }}
  flannel_docker_tag: v0.7.1-amd64
  kube-apiserver_docker_tag: {{ version }}
  kube-controller-manager_docker_tag: {{ version }}
  kube-scheduler_docker_tag: {{ version }}
  kube-proxy_docker_tag: {{ version }}
  service_cluster_ip_range: "10.254.0.0/16"
  cluster_cidr: "10.150.0.0/16"
  master_extra_sans: "IP:10.254.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local"
  advertise_address: {{ ips[0] }}
  flannel_bind_iface: eth0
  flannel_backend_mode: vxlan
  admin:
    username: admin
    password: admin
  token:
    admin: DFvQ8GJ9JD4fKNfuyEddw3rjnFTkUKsv
    controller_manager: EreGh6AnWf8DxH8cYavB2zS029PUi7vx
    dns: RAFeVSE4UvsCz4gk3KYReuOI5jsZ1Xt3
    kube_proxy: DFvQ8GelB7afH3wClC9romaMPhquyyEe
    kubelet:  7bN5hJ9JD4fKjnFTkUKsvVNfuyEddw3r
    logging: MJkXKdbgqRmTHSa2ykTaOaMykgO6KcEf
    monitoring: hnsj0XqABgrSww7Nqo7UVTSZLJUt2XRd
    scheduler: HY1UUxEPpmjW4a1dDLGIANYQp1nZkLDk
  
  
  addons:
    logging: True
    monitoring: True
  
  # etcd
  keep_host_etcd: False
  # Addons
  # dns
  enable_cluster_dns: True
  dns_server: 10.254.254.254
  dns_domain: cluster.local
  federations_domain_map: ""
  # dashboard
  enable_cluster_ui: True
      