{% set version = "v1.7.0" %}

{% set master_nodes = salt['mine.get']('kubernetes:master', 'network.internal_ip', 'pillar') -%}
{% set master_ips = master_nodes.values() -%}

{% set pool_nodes = salt['mine.get']('kubernetes:pool', 'network.internal_ip', 'pillar') -%}

kubernetes:
  version: {{ version }}
  hyperkube_image: gcr.io/google_containers/hyperkube
  flannel_image: "quay.io/coreos/flannel"
  {% if grains['oscodename'] in [ 'vivid', 'wily', 'jessie', 'xenial', 'yakkety' ] %}
  is_systemd: True
  systemd_system_path: /lib/systemd/system
  {% elif grains['os_family'] == 'RedHat' %}
  is_systemd: True
  systemd_system_path: /usr/lib/systemd/system
  {% else %}
  is_systemd: False
  {% endif %}
  admission_control: "NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds"
  kube_user: "system:anonymous"
  network_provider: "kubenet"
  cni_provider: "flannel"
  allow_privileged: true
  log_level: "--v=0"
  kube_docker_registry: "gcr.io/google_containers"
  apiserver_docker_tag: {{ version }}
  flannel_docker_tag: v0.7.1-amd64
  kube-apiserver_docker_tag: {{ version }}
  kube-controller-manager_docker_tag: {{ version }}
  kube-scheduler_docker_tag: {{ version }}
  kube-proxy_docker_tag: {{ version }}
  
  service_cluster_ip_range: "10.254.0.0/16"
  cluster_cidr: "10.150.0.0/16"
  minion_id_as_hostname: false
  api_server:
    ip: {{ master_ips[0] }}
    port: 6443
    fqdn: kubernetes.api
    register_schedulable: false
  master_extra_sans: "IP:10.254.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local"
  master_nodes: {{master_nodes}}
  master_ips: {{master_ips}}
  pool_nodes: {{pool_nodes}}
  bind_iface: eth0
  flannel:
    enable_calico: true
    backend_mode: vxlan
  admin:
    username: admin
    password: admin
  token:
    admin: DFvQ8GJ9JD4fKNfuyEddw3rjnFTkUKsv
    controller_manager: EreGh6AnWf8DxH8cYavB2zS029PUi7vx
    dns: RAFeVSE4UvsCz4gk3KYReuOI5jsZ1Xt3
    kube_proxy: DFvQ8GelB7afH3wClC9romaMPhquyyEe
    kubelet:  7bN5hJ9JD4fKjnFTkUKsvVNfuyEddw3r
    logging: MJkXKdbgqRmTHSa2ykTaOaMykgO6KcEf
    monitoring: hnsj0XqABgrSww7Nqo7UVTSZLJUt2XRd
    scheduler: HY1UUxEPpmjW4a1dDLGIANYQp1nZkLDk
  
  addons:
    logging: True
    monitoring: True
  # storage class
  enable_default_storage_class: False
  default_storage_class_zones: ""
  # etcd
  keep_host_etcd: False
  # Addons
  # dashboard
  enable_cluster_ui: True
  # rescheduler
  enable_rescheduler: True
  # cluster_autoscaler
  cluster_autoscaler: 
    enabled: False
    params: []
  # dns
  enable_cluster_dns: True
  dns_server: 10.254.254.254
  dns_domain: cluster.local
  federations_domain_map: ""

      