{% set version = "v1.6.0" %}
kubernetes:
  version: {{ version }}
  hyperkube_image: gcr.io/google_containers/hyperkube
  {% if grains['oscodename'] in [ 'vivid', 'wily', 'jessie', 'xenial', 'yakkety' ] %}
  is_systemd: True
  systemd_system_path: /lib/systemd/system
  {% elif grains['os_family'] == 'RedHat' %}
  is_systemd: True
  systemd_system_path: /usr/lib/systemd/system
  {% else %}
  is_systemd: False
  {% endif %}
  network_provider: "kubenet"
  allow_privileged: true
  log_level: "--v=2"
  kube_docker_registry: "gcr.io/google_containers"
  apiserver_docker_tag: {{ version }}
  kube-apiserver_docker_tag: {{ version }}
  kube-controller-manager_docker_tag: {{ version }}
  kube-scheduler_docker_tag: {{ version }}
  kube-proxy_docker_tag: {{ version }}
  service_cluster_ip_range: "10.254.0.0/16"
  cluster_cidr: "10.150.0.0/16"
  admin:
    username: admin
    password: admin
  certs:
    'ca.crt': |
        -----BEGIN CERTIFICATE-----
        MIIDWTCCAkGgAwIBAgIJAPNzYb2UDOAdMA0GCSqGSIb3DQEBCwUAMCIxIDAeBgNV
        BAMUFzE5Mi4xNjguNTEuNUAxNDk5NDAyMDc0MB4XDTE3MDcwNzA0MzQzNFoXDTI3
        MDcwNTA0MzQzNFowIjEgMB4GA1UEAxQXMTkyLjE2OC41MS41QDE0OTk0MDIwNzQw
        ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCzOgHWFyEGkRS3XMT6X+O/
        PXEUFOTCmSK9q6ZhOgQShB0tlbMKTTJLXOXGSttInyn1Q6TSd+kZSHcjV1ZjY/X6
        u/ZpGSwFSH3OtQgCdYfMlH/vr/znuvi+wUtSSS80cC9XOY6lgpswBWIH05hHKWvv
        9+tNJ+Kc15uyWdn9QFn1jDX1L/duWkg9ERXGrgs6i3jN18yuoyYxwzkMdcLkboa8
        bxwqHtdVQ6Jgj82H6KaVOuLt1sCL8ne/PiWaiGzW5C35qpw9ylgqUYDZdd/2Dj3M
        Ml1a7LYCgfll1Ca6OZL0wWA6nS5lZit4xG/fhKzvdI6EHlbbEvF/ExkLk5RXeAxv
        AgMBAAGjgZEwgY4wHQYDVR0OBBYEFKU/rS76eeI9lcOCtvQk2PqRshu1MFIGA1Ud
        IwRLMEmAFKU/rS76eeI9lcOCtvQk2PqRshu1oSakJDAiMSAwHgYDVQQDFBcxOTIu
        MTY4LjUxLjVAMTQ5OTQwMjA3NIIJAPNzYb2UDOAdMAwGA1UdEwQFMAMBAf8wCwYD
        VR0PBAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IBAQBPgxZEL4WBEbZlvoalKrd0wKe4
        uQ97D8F8XtugkjSWgmi9eFGPMuevNCOkx/KWnRBzOkWN/q+Y6RdEgpe6I5tHNsu6
        TPjwkVbSwkBpnsUmJdl+UE+JsWD6hX+Mf1qBJD8e8LXjv4UU43f4zrXoZNAGGGQR
        UgwmSQitemstYcUO3D8n+nj62ryJ6WFfFq/jswl5iC2Geai/BP/O0C6yl972FMAV
        thPqWFdyBrDMTmIdsmZn6iCjRtGfITa5CWWwqK64ZuT4+4fmqoK3tjiWBERHJ7Af
        zqIlaPnNxKEAe+GuLr6afEQvIaNgrsRxc7QXKrFuZcKHh+WT5ctV3bwSy9Yq
        -----END CERTIFICATE-----
    'server.key': |
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDQBzvKIO+9/9+x
        CbXZ6OeBwwcHDjiul0oQbD3+w/m6XWt5sf5XaoTgjC8TLiuNmdv2Cce+RCaRxn+P
        GrlaTltZdJaJs1Cn5TVG26btC8Hxpv/DVTHon8JtzsLWevuAoO2/YKpWR7FhkjHs
        pLkXdU5DZBBb/A1SG9XeL72xy+Oe/skISfdtxO4g1yH1TkI5+67VHnTStyvKruRn
        sGsw3OT37DqlJ25mniI8mHaupVJIHITGyduxIoM05EEpmTHSxZPOjSVRfd/vC0ob
        DThsvKSlIWDDR7aH/5vceJlUbeOxp8o6/g7/NhIMmplYAF3d/u7oWRQS0ld4e0R1
        o+lEZTJ3AgMBAAECggEBAKU5WY+M4V1y4OPn5nuQtG8ny2kbLoHcv4KTthmm5a3T
        jQ03Bd/ARpFiRfFh9k2dKkscMX04+7lEgwPSIe1L1toR846i0SjIr6v7wXT8pamd
        Df7Cp8UvPmmgkrdvLlpXdv1NdXzZrFTmnKhrnGa5UNPNogCtDJdubErweCXC3qLk
        I0ArfvtZq8Cyvs0SeVy4C2U4blNhrPVg0EPZI5F+XgJJ/oSdXwUKtlBOL7a0tPkY
        KrYtRbbtoSvXOKo0M3oVCJumDvDH0cZAizCjiSfOgR7IgQZWR7avtzlMpGhEf9qE
        aaHcKptM/Gj0su3JlF3YsUATbre13gJNbigslZYEsOECgYEA8CtQkR1MpqLrPKIJ
        oLrP8NH2pwgvMx1HFfIgW8OJpWOzkYYoAlz6Azo51I95IVog1TB0+lpEkRvjMhEQ
        jWIfm0znmei5dnkHdO+3cqF3SYGLsYLW3y7/+3bQXkMegMM3sPvcFCTkYjLiAPOu
        p4tyiI2pN8YhqkDYZmFcHzmvDVMCgYEA3b2QLMcNo2kTa6urrw4f/0KeyURxRHsN
        9Bb4ROJjNI8gSEKG7c5g7C4UbZJfnfJONqrty9EEgOns83fsD0BPZdz+RmxLc7hM
        48e9H7OCD6sfBSr2MSD5Q00bOoMms+2wY1edxwmnSLKCEDSmX2RTyVLQhebNfRPa
        vEsdP5Kyfc0CgYEAzbXsDj+wVdKZ9pc78+XPEhBlWfBSrU9Ygd2gBblYfscFGZJ1
        VoDYzEblHcG+GOkf0jrtFzqWHExsr4eaS99N/zFB9rw1jtpfnrNsx8yxZc6GHodZ
        EFUrgPHly7dluxh67Sbs/HwU+l9m4TXX1T5F3dyoolMcpr1gHWErDLvVym0CgYB0
        xcx0WEtNYBuTGy/pm2WsVpgqY/nGV4tsnOAX3qTh2/HjO+20tHeESWwGnAvwsNcR
        oQhjymo1vXtEaEYPbg2iFjRuP7+obElJtzlYxX7b44ENhqdqDfRWxfdt4/1wyd6X
        Il/7npDTDvbBtAhdugcJwawAqCBVGyyY9nGrtgR7jQKBgG8xNKndbJsxNmgFg83Q
        DZpCnaSP4t6WdV8yzFaYQnyohwp6bgNxR5wW+wXGnWCc41hv2Rz9xICgeEJJbprR
        RX4Tf5VqEoUYvWIznaWW9wC6l/NfcxTZyDtJrppVBLrLAWuQF2+sSFf+yBRsdd88
        Xy+uhRfnRtzMxkeTg296Ztpt
        -----END PRIVATE KEY-----
    'server.cert': |
        Certificate:
            Data:
                Version: 3 (0x2)
                Serial Number: 1 (0x1)
            Signature Algorithm: sha256WithRSAEncryption
                Issuer: CN=192.168.51.5@1499402074
                Validity
                    Not Before: Jul  7 04:34:34 2017 GMT
                    Not After : Jul  5 04:34:34 2027 GMT
                Subject: CN=kubernetes-master
                Subject Public Key Info:
                    Public Key Algorithm: rsaEncryption
                        Public-Key: (2048 bit)
                        Modulus:
                            00:d0:07:3b:ca:20:ef:bd:ff:df:b1:09:b5:d9:e8:
                            e7:81:c3:07:07:0e:38:ae:97:4a:10:6c:3d:fe:c3:
                            f9:ba:5d:6b:79:b1:fe:57:6a:84:e0:8c:2f:13:2e:
                            2b:8d:99:db:f6:09:c7:be:44:26:91:c6:7f:8f:1a:
                            b9:5a:4e:5b:59:74:96:89:b3:50:a7:e5:35:46:db:
                            a6:ed:0b:c1:f1:a6:ff:c3:55:31:e8:9f:c2:6d:ce:
                            c2:d6:7a:fb:80:a0:ed:bf:60:aa:56:47:b1:61:92:
                            31:ec:a4:b9:17:75:4e:43:64:10:5b:fc:0d:52:1b:
                            d5:de:2f:bd:b1:cb:e3:9e:fe:c9:08:49:f7:6d:c4:
                            ee:20:d7:21:f5:4e:42:39:fb:ae:d5:1e:74:d2:b7:
                            2b:ca:ae:e4:67:b0:6b:30:dc:e4:f7:ec:3a:a5:27:
                            6e:66:9e:22:3c:98:76:ae:a5:52:48:1c:84:c6:c9:
                            db:b1:22:83:34:e4:41:29:99:31:d2:c5:93:ce:8d:
                            25:51:7d:df:ef:0b:4a:1b:0d:38:6c:bc:a4:a5:21:
                            60:c3:47:b6:87:ff:9b:dc:78:99:54:6d:e3:b1:a7:
                            ca:3a:fe:0e:ff:36:12:0c:9a:99:58:00:5d:dd:fe:
                            ee:e8:59:14:12:d2:57:78:7b:44:75:a3:e9:44:65:
                            32:77
                        Exponent: 65537 (0x10001)
                X509v3 extensions:
                    X509v3 Basic Constraints:
                        CA:FALSE
                    X509v3 Subject Key Identifier:
                        E1:B2:90:74:8C:A1:5A:83:4C:B0:BA:15:3B:3C:51:8D:B9:1F:86:02
                    X509v3 Authority Key Identifier:
                        keyid:A5:3F:AD:2E:FA:79:E2:3D:95:C3:82:B6:F4:24:D8:FA:91:B2:1B:B5
                        DirName:/CN=192.168.51.5@1499402074
                        serial:F3:73:61:BD:94:0C:E0:1D

                    X509v3 Extended Key Usage:
                        TLS Web Server Authentication
                    X509v3 Key Usage:
                        Digital Signature, Key Encipherment
                    X509v3 Subject Alternative Name:
                        IP Address:192.168.51.5
            Signature Algorithm: sha256WithRSAEncryption
                 61:00:90:41:66:2b:e6:62:28:ac:6a:9b:92:1d:cc:13:65:b8:
                 5a:fe:23:17:fd:e4:82:af:d6:95:06:92:e5:87:0b:22:16:98:
                 3d:29:6d:ce:66:f0:9a:f2:56:5b:48:97:25:25:1c:47:39:5b:
                 25:8c:56:19:bc:b3:73:8d:29:0a:c3:6f:bb:9e:bd:a0:01:22:
                 7b:f8:82:4c:cf:a8:b7:c6:2d:c8:53:c8:e1:9b:d8:9e:9f:76:
                 1d:a0:4a:f2:aa:35:f7:13:08:e7:9b:0c:38:e3:a3:47:a2:66:
                 6f:ee:4c:c4:0f:0d:eb:97:e4:aa:75:2a:dd:e8:0d:06:d0:79:
                 10:4e:97:7d:01:5b:12:d8:2e:d2:42:c4:cb:31:e1:08:66:52:
                 4e:22:f5:e6:d5:b6:1f:1d:93:00:4c:d0:9c:86:4d:44:36:5e:
                 0b:b1:c1:9b:96:da:cd:bc:d8:c3:6d:cc:75:84:c4:38:59:55:
                 94:03:10:a6:21:8a:0e:af:8f:9d:08:2a:0a:ae:ee:c6:4c:c9:
                 e1:a4:2c:ea:f5:5f:b2:9f:5b:33:05:a7:93:49:88:3c:b4:bb:
                 de:5a:e2:b0:03:c5:e8:24:27:cf:00:cd:b0:7b:55:76:6b:55:
                 03:b0:79:eb:e5:71:2f:e1:ac:09:c9:b0:b8:48:0d:8f:c0:d3:
                 98:08:01:e9
        -----BEGIN CERTIFICATE-----
        MIIDbjCCAlagAwIBAgIBATANBgkqhkiG9w0BAQsFADAiMSAwHgYDVQQDFBcxOTIu
        MTY4LjUxLjVAMTQ5OTQwMjA3NDAeFw0xNzA3MDcwNDM0MzRaFw0yNzA3MDUwNDM0
        MzRaMBwxGjAYBgNVBAMTEWt1YmVybmV0ZXMtbWFzdGVyMIIBIjANBgkqhkiG9w0B
        AQEFAAOCAQ8AMIIBCgKCAQEA0Ac7yiDvvf/fsQm12ejngcMHBw44rpdKEGw9/sP5
        ul1rebH+V2qE4IwvEy4rjZnb9gnHvkQmkcZ/jxq5Wk5bWXSWibNQp+U1Rtum7QvB
        8ab/w1Ux6J/Cbc7C1nr7gKDtv2CqVkexYZIx7KS5F3VOQ2QQW/wNUhvV3i+9scvj
        nv7JCEn3bcTuINch9U5COfuu1R500rcryq7kZ7BrMNzk9+w6pSduZp4iPJh2rqVS
        SByExsnbsSKDNORBKZkx0sWTzo0lUX3f7wtKGw04bLykpSFgw0e2h/+b3HiZVG3j
        safKOv4O/zYSDJqZWABd3f7u6FkUEtJXeHtEdaPpRGUydwIDAQABo4G0MIGxMAkG
        A1UdEwQCMAAwHQYDVR0OBBYEFOGykHSMoVqDTLC6FTs8UY25H4YCMFIGA1UdIwRL
        MEmAFKU/rS76eeI9lcOCtvQk2PqRshu1oSakJDAiMSAwHgYDVQQDFBcxOTIuMTY4
        LjUxLjVAMTQ5OTQwMjA3NIIJAPNzYb2UDOAdMBMGA1UdJQQMMAoGCCsGAQUFBwMB
        MAsGA1UdDwQEAwIFoDAPBgNVHREECDAGhwTAqDMFMA0GCSqGSIb3DQEBCwUAA4IB
        AQBhAJBBZivmYiisapuSHcwTZbha/iMX/eSCr9aVBpLlhwsiFpg9KW3OZvCa8lZb
        SJclJRxHOVsljFYZvLNzjSkKw2+7nr2gASJ7+IJMz6i3xi3IU8jhm9ien3YdoEry
        qjX3Ewjnmww446NHomZv7kzEDw3rl+SqdSrd6A0G0HkQTpd9AVsS2C7SQsTLMeEI
        ZlJOIvXm1bYfHZMATNCchk1ENl4LscGbltrNvNjDbcx1hMQ4WVWUAxCmIYoOr4+d
        CCoKru7GTMnhpCzq9V+yn1szBaeTSYg8tLveWuKwA8XoJCfPAM2we1V2a1UDsHnr
        5XEv4awJybC4SA2PwNOYCAHp
        -----END CERTIFICATE-----
      
  token:
    admin: DFvQ8GJ9JD4fKNfuyEddw3rjnFTkUKsv
    controller_manager: EreGh6AnWf8DxH8cYavB2zS029PUi7vx
    dns: RAFeVSE4UvsCz4gk3KYReuOI5jsZ1Xt3
    kube_proxy: DFvQ8GelB7afH3wClC9romaMPhquyyEe
    kubelet: 7bN5hJ9JD4fKjnFTkUKsvVNfuyEddw3r
    logging: MJkXKdbgqRmTHSa2ykTaOaMykgO6KcEf
    monitoring: hnsj0XqABgrSww7Nqo7UVTSZLJUt2XRd
    scheduler: HY1UUxEPpmjW4a1dDLGIANYQp1nZkLDk
  kube_user: 'system:anonymous'
  addons:
    logging: True
    monitoring: True
  # etcd
  keep_host_etcd: False
